services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - news_api-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=newsflow
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
    ports:
      - "27017:27017"
networks:
  news_api-network:
    driver: bridge